config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :articles
  # asオプションはplefixを生成する
  get 'checks/:id', to: 'checks#check', as: 'check'
    get 'checks/revert/:id', to: 'checks#revert_check'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :checks, dependent: :destroy
  has_many :users, through: :checks
  has_one_attached :image

  with_options presence: true do
    validates :image
    validates :title, length: { maximum: 20}
    validates :content
    validates :about_time
    validates :user_id
  end
end

app/models/check.rb
class Check < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :checks, dependent: :destroy
  has_many :articles, through: :checks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :authenticate_user!
  before_action :if_not_admin, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  
  def index
    @articles = Article.all.order("created_at DESC")
    @ranking_articles = Article.order("RAND()").limit(10)
  end

  def show
    
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      return redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if @article.update(article_params)
      return redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      return redirect_to root_path
    else
      render 'show'
    end
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def article_params
    params.require(:article).permit(
      :title,
      :content,
      :about_time,
      :image
    ).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def check
    # find_or_create_byとは、「レコードがなければ作り、あればレコード情報を返す」というメソッド
    Check.find_or_create_by(user_id: current_user.id, article_id: @article.id)
    # 既読のレコードを作成したら詳細ページを表示
    redirect_to controller: :articles, action: :show
  end

  def revert_check
    check.find_by(user_id: current_user.id,article_id: @article.id).destroy
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/views/articles/edit.html.erb
<%= render "shared/header" %>

<div class="post-article-form">
  <%= form_with(model: @article, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <p><%= f.label :title, '記事名' %><span>（必須・20文字以内）</span></p>
    <%= f.text_field :title, class:"new-article-title", placeholder: "記事名" %>
    <p><%= f.label :content, '記事内容' %><span>（必須）</span></p>
    <%= f.text_area :content, class:"new-article-content", placeholder: "記事内容" %>
    <p><%= f.label :image, 'アイキャッチ画像' %><span>（必須）</span></p>
    <%= f.file_field :image, class:"new-article-image", id:"new-article-image" %>
    <p><%= f.label :about_time, '目安所要時間' %><span>（必須）</span></p>
    <%= f.select :about_time,{'5分': 5, '10分': 10, '15分': 15, '20分': 20}, { include_blank: '5~20分で選択してください'}, {class:"new-article-about_time"} %>
    <%= f.submit "投稿", class:"new-article-submit_btn" %>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/articles/index.html.erb
<%= render "shared/header" %>

<div class="main-contents">
  <div class="articles">
    <% @articles.each do |article| %>
      <div class="article" id=<%= article.id%>>
        <div class="article-overview">
          <%= link_to check_path(article) do %>
            <p class="article-title">
              <%= article.title%>
            </p>
            <p class="article-content">
              <%= article.content%>
            </p>
          <% end %>
          <div class="article-information">
            <p class="article-post-date">
              <%= article.created_at.strftime("%Y年 %m月 %d日") %>
            </p>
            <p class="article-about-time">
              目安時間：<%= article.about_time %>分
            </p>
            <div class="article-check">
              <% if Check.where(user_id: current_user.id, article_id: article.id).exists? %>
                <div class="article-check-button" data=<%= article.id %>>
                  既読
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <%= image_tag article.image.variant(resize_to_fill: [400, 400]), class: "article-image" %>
      </div>
    <% end %>
  </div>

  <div class="ranking">
    <p class="ranking-name">
      週間ランキング
    </p>
    <div class="ranking-articles">
      <% @ranking_articles.each_with_index do |r_article, i| %>
      <div class="ranking-article">
          <p class="weekly-rank">
            <%= i+1 %>
          </p>
          <div class="ranking-overview">
            <%= link_to article_path(r_article) do %>
              <%= image_tag r_article.image.variant(resize_to_fill: [400, 400]), class: "ranking-article-image" %>
              <div class="ranking-article-title">
                <%= r_article.title%>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/articles/new.html.erb
<%= render "shared/header" %>

<div class="post-article-form">
  <%= form_with(model: @article, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <p><%= f.label :title, '記事名' %><span>（必須・20文字以内）</span></p>
    <%= f.text_field :title, class:"new-article-title", placeholder: "記事名" %>
    <p><%= f.label :content, '記事内容' %><span>（必須）</span></p>
    <%= f.text_area :content, class:"new-article-content", placeholder: "記事内容" %>
    <p><%= f.label :image, 'アイキャッチ画像' %><span>（必須）</span></p>
    <%= f.file_field :image, class:"new-article-image", id:"new-article-image" %>
    <p><%= f.label :about_time, '目安所要時間' %><span>（必須）</span></p>
    <%= f.select :about_time,{'5分': 5, '10分': 10, '15分': 15, '20分': 20}, { include_blank: '5~20分で選択してください'}, {class:"new-article-about_time"} %>
    <%= f.submit "投稿", class:"new-article-submit_btn" %>
  <% end %>
</div>

<%= render "shared/footer" %>

app/views/articles/show.html.erb
<%= render "shared/header" %>
<div class="show-article">
  <p class="show-article-title">
    <%= @article.title %>
  </p>
  <p class="show-article-post-date">
    <%= @article.created_at.strftime("%Y年 %m月 %d日") %>
  </p>
  <%= image_tag @article.image.variant(resize: '500x500'), class: "show-article-image" %>
  <p class="show-article-content">
    <%= @article.content %>
  </p>
</div>

<% if current_user.admin == true %>
  <div class="change-article">
    <div class="edit-article">
      <%= link_to "編集", edit_article_path(@article), class:"edit-btn" %>
    </div>
    <div class="delete-article">
      <%= link_to "削除", article_path(@article), method: :delete, class:"delete-btn" %>
    </div>
  </div>
<% end %>

<div class="return-toppage">
  <%= link_to "トップページへ戻る", root_path, class:"return-btn" %>
</div>

<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsappRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%=link_to image_tag("/images/mini-logo.png", class:"fotter-logo"), "/" %>
</div>

app/views/shared/_header.html.erb
<div class="header"> 
  <div class="logo">
    <%= link_to image_tag("/images/big-logo.png", class:"header-icon"), "/" %>
  </div>
  <div class="header-btn">
    <% if current_user.admin%>
      <%= link_to '記事を投稿する', new_article_path, class:"post-article-btn"%>
    <% end %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout-btn"%>
  </div>
  <div class="menu-bar">
    <ul class="menu-elements">
      <li id="menu1">
        メニュー1
        <ul class="menu1-lists hidden" id="menu1-pull-down">
          <li>リスト1</li>
          <li>リスト2</li>
          <li>リスト3</li>
          <li>リスト4</li>
        </ul>
      </li>
      <li id="menu2">
        メニュー2
      </li>
      <li id="menu3">
        メニュー3
      </li>
    </ul>
  </div>
</div>